import asyncio
import json
from abc import ABC, abstractmethod

class BaseAgentAdapter(ABC):
    @abstractmethod
    async def execute_task(self, prompt: str, system_instruction: str, context_artifacts: dict = None) -> str:
        pass

class MockAgentAdapter(BaseAgentAdapter):
    async def execute_task(self, prompt: str, system_instruction: str, context_artifacts: dict = None) -> str:
        await asyncio.sleep(0.4) # Realistic network feel
        
        system_lower = system_instruction.lower()
        
        # 1. ASSEMBLER MOCK
        if "assembler" in system_lower:
            customer_data = context_artifacts.get("raw_customer", {}) if context_artifacts else {}
            return f"""# Compiled Customer 360 Consolidated Profile
**Assembled by Context Assembler Agent**

## 👤 CRM Registry Details
- **Account Name:** {customer_data.get('crm', {}).get('name', 'N/A')} (ID: {customer_data.get('crm', {}).get('id', 'N/A')})
- **Client Tier:** {customer_data.get('crm', {}).get('tier', 'N/A')}
- **Account Status:** {customer_data.get('crm', {}).get('status', 'N/A')}
- **Signup Date:** {customer_data.get('crm', {}).get('signup_date', 'N/A')}

## 💳 Billing Ledger Summary
- **Outstanding Balances:** ${customer_data.get('billing', {}).get('outstanding_balance', 0.0):.2f}
- **Last Invoice Status:** {customer_data.get('billing', {}).get('last_invoice_status', 'N/A')}
- **Registered Method:** {customer_data.get('billing', {}).get('payment_method', 'N/A')}

## 📊 Product Usage Telemetry
- **API Requests (30d):** {customer_data.get('telemetry', {}).get('api_calls_30d', 0)} calls
- **Daily Active Days (30d):** {customer_data.get('telemetry', {}).get('daily_active_days', 0)} / 30 days
- **Active Support Tickets:** {customer_data.get('telemetry', {}).get('support_tickets_30d', 0)} tickets

## 🩺 System Computed Health Indices
- **Calculated Health Score:** {customer_data.get('calculated_health_score', 100)} / 100
- **Computed Posture Status:** {customer_data.get('calculated_health_status', 'Happy')}
"""

        # 2. PROACTIVE OUTREACH MOCK
        elif "proactive" in system_lower:
            customer_name = context_artifacts.get("customer_name", "Valued Customer") if context_artifacts else "Valued Customer"
            event_type = context_artifacts.get("event_type", "Telemetry Shift") if context_artifacts else "Telemetry Shift"
            
            return f"""# Proposed Proactive Outreach Campaign Strategy
**Generated by Proactive Outreach Specialist**

## Churn Risk Analysis
- **Observed Event Alert:** {event_type}
- **Client Group:** High-Priority Customer Account

## 📋 Campaign Outreach Pitch
Dear CEO of {customer_name},

We noticed some recent changes in your active login telemetry patterns. As an enterprise partner, your operational success is our top goal. 

We would love to offer you a **30% subscription invoice credit** for the next 3 billing cycles, alongside a free 1-hour engineering consultation session with our principal solutions architect to resolve any roadblocks.

Please let us know if you'd like to schedule this!

Best regards,
Partner Success Swarm
"""

        # 3. DIAGNOSTICS SPECIALIST MOCK
        elif "diagnostic" in system_lower:
            customer_name = context_artifacts.get("customer_name", "Valued Customer") if context_artifacts else "Valued Customer"
            balance = context_artifacts.get("balance", 0.0) if context_artifacts else 0.0
            
            return f"""# Proposed Settlement & Resolution Voucher
**Generated by Diagnostics & Support Specialist**

## Core Support Diagnosis
- **Client Concern:** Payment Failures on Invoice and balance collection disputes.
- **Ledger Invoice Balance:** ${balance:.2f}

## ⚙ Proposed Account Modification Action
- **Account Actions:** Propose a **${balance:.2f} settlement waiver balance refund** to settle the billing ledger mismatch.
- **Client Messaging Copy:**

Dear {customer_name},

We resolved the ledger discrepancies on your billing account. To ensure seamless API gateways access, we have processed a temporary **${balance:.2f} waiver adjustment** to your outstanding invoice balance. 

Your payment credentials have been verified. Access is fully reinstated.

Best regards,
Enterprise Billing Support
"""

        # 4. QA COMPLIANCE MOCK
        elif "qa" in system_lower or "compliance" in system_lower:
            outreach = context_artifacts.get("proposed_outreach", "") if context_artifacts else ""
            is_polite = "dear" in outreach.lower()
            
            status = "PASSED" if is_polite else "FAILED"
            score = 100 if is_polite else 40
            
            return f"""# QA Compliance & Policy Certificate
**Issued by QA Compliance Auditor Specialist**

## 🔍 Validation Scorecard
- **Audit Verification Score:** {score} / 100
- **Brand Tone Compliance Pass:** {status}
- **Financial Audit Verification:** PASSED (all proposed adjustments match database invoices)

## 📌 Certification Details
- [x] Verified zero aggressive, non-compliant collection messaging patterns.
- [x] Confirmed customer account and invoice refund numbers match ledger balance records.
- [x] Validated professional, proactive, and brand-supportive posture.
"""

        return "Processed servicing state."

def get_agent_adapter() -> BaseAgentAdapter:
    return MockAgentAdapter()
